language: r
r: bioc-devel
cache: packages
sudo: true

bioc_packages:
  - BiocStyle

# before_install:
#   - tlmgr install bera nowidow parnotes marginfix

apt_packages:
  - libnetcdf-dev
  - texlive-full  
  
after_success:
  - Rscript -e 'covr::codecov()'

# print timings (of examples) and sysinfo
after_script:
  - dump_logs_by_extension "timings"
  - dump_sysinfo

notifications:
  email:
    on_failure: lg390@cam.ac.uk

