language: r
r: bioc-devel
cache: packages
sudo: false       # use container based build system
warnings_are_errors: true

before_install:
  - tlmgr install bera nowidow parnotes marginfix etoolbox titlesec sectsty framed enumitem parskip soul placeins footmisc changepage xstring caption mathtools 

addons:
  apt:
    packages:
      - texlive-latex-extra
      - texlive-fonts-extra
      - libnetcdf-dev
      - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 it is part of libnetcdf-dev)

r_packages:
  - covr
  - Rcpp
  - progress
  - DBI
  - ggplot2
  - RSQLite
  - XML
  - MALDIquant

bioc_packages:
  - AnnotationDbi
  - annotate
  - mzR
  - BiocParallel
  - mzID

after_success:
  - Rscript -e 'covr::codecov()'

# print timings (of examples) and sysinfo
after_script:
  - dump_logs_by_extension "timings"
  - dump_sysinfo

notifications:
  email:
    on_failure: lg390@cam.ac.uk

