language: r
r: bioc-devel
cache: packages
sudo: true

apt_packages:
  - libnetcdf-dev
  - texlive-fonts-extra
  
    
after_success:
  - Rscript -e 'covr::codecov()'

# print timings (of examples) and sysinfo
after_script:
  - dump_logs_by_extension "timings"
  - dump_sysinfo

notifications:
  email:
    on_failure: lg390@cam.ac.uk

