language: r
r: bioc-devel
cache: packages
sudo: true

before_install:
  - tlmgr install bera nowidow parnotes marginfix ifthen etoolbox titlesec sectsty framed enumitem parskip authblk soul placeins ragged2e footmisc changepage xstring caption titletoc mathtools 

apt_packages:
  - libnetcdf-dev
  - texlive-full  
  
after_success:
  - Rscript -e 'covr::codecov()'

# print timings (of examples) and sysinfo
after_script:
  - dump_logs_by_extension "timings"
  - dump_sysinfo

notifications:
  email:
    on_failure: lg390@cam.ac.uk

